name: Deploy AWS Staging Environment

on:
  push:
    paths:
      - 'aws/stage/**'
# workflow dispatch is used if you want to manually run deployments from GitHub, this is not adviced without adding any verification, however for setting up and testing it can be left as is
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform
        working-directory: aws/stage/services
        run: terraform init -backend-config=backend.hcl
      
      - name: Apply Terraform changes
        working-directory: aws/stage/services
        run: terraform apply -auto-approve
