name: Deploy Production Environment

on:
  push:
    paths:
      - 'aws/prod/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Change to services directory
        run: cd aws/prod/services

      - name: Initialize Terraform
        run: terraform init -backend-config=backend.hcl
      
      - name: Apply Terraform changes
        run: terraform apply
